#!/usr/bin/env bash
# deploy the basket factory and a demo basket, then write the frontend env file
#
# usage:
#   scripts/deploy.sh local     deploy to a running anvil node on localhost:8545
#   scripts/deploy.sh testnet   deploy to robinhood chain testnet (chain id 46630)
#   scripts/deploy.sh mainnet   deploy to robinhood chain mainnet (chain id 4663)
#
# environment:
#   PRIVATE_KEY   deployer key, required for testnet and mainnet
#   RPC_URL       override the default rpc endpoint for the chosen target
#   VERIFY        set to 0 to skip blockscout verification on testnet and mainnet

set -Eeuo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    sed -n '2,13p' "$0"
    exit 0
fi

TARGET="${1:-local}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/apps/frontend/.env.local"

# ----- config -----

# anvil default account zero, a public test key, never use this pattern on live networks
ANVIL_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

case "$TARGET" in
local)
    RPC_URL="${RPC_URL:-http://localhost:8545}"
    PRIVATE_KEY="${PRIVATE_KEY:-$ANVIL_KEY}"
    CHAIN_ID=31337
    VERIFIER_URL=""
    ;;
testnet)
    RPC_URL="${RPC_URL:-https://rpc.testnet.chain.robinhood.com}"
    CHAIN_ID=46630
    VERIFIER_URL="https://explorer.testnet.chain.robinhood.com/api/"
    ;;
mainnet)
    RPC_URL="${RPC_URL:-https://rpc.mainnet.chain.robinhood.com}"
    CHAIN_ID=4663
    VERIFIER_URL="https://robinhoodchain.blockscout.com/api/"
    ;;
*)
    echo "unknown target: $TARGET (expected local, testnet, or mainnet)" >&2
    exit 1
    ;;
esac

# ----- preflight -----

command -v forge >/dev/null || {
    echo "forge not found, install foundry: https://getfoundry.sh" >&2
    exit 1
}

if [[ "$TARGET" != "local" && -z "${PRIVATE_KEY:-}" ]]; then
    echo "PRIVATE_KEY is required for $TARGET deploys" >&2
    exit 1
fi

ACTUAL_CHAIN_ID=$(cast chain-id --rpc-url "$RPC_URL")
if [[ "$ACTUAL_CHAIN_ID" != "$CHAIN_ID" ]]; then
    echo "rpc $RPC_URL reports chain id $ACTUAL_CHAIN_ID, expected $CHAIN_ID" >&2
    exit 1
fi

# ----- deploy -----

echo "deploying to $TARGET (chain id $CHAIN_ID) via $RPC_URL" >&2

VERIFY_ARGS=()
if [[ -n "$VERIFIER_URL" && "${VERIFY:-1}" == "1" ]]; then
    VERIFY_ARGS=(--verify --verifier blockscout --verifier-url "$VERIFIER_URL")
fi

# gas estimates on arbitrum stack chains include an l1 data fee component that
# moves between estimation and execution, extra headroom prevents out of gas
# --slow waits for each receipt so later txs never race earlier deployments
OUTPUT=$(cd "$ROOT/contracts" && forge script script/Deploy.s.sol:Deploy \
    --rpc-url "$RPC_URL" \
    --private-key "$PRIVATE_KEY" \
    --broadcast \
    --slow \
    --gas-estimate-multiplier 300 \
    ${VERIFY_ARGS[@]+"${VERIFY_ARGS[@]}"} 2>&1) || {
    echo "$OUTPUT" >&2
    exit 1
}

echo "$OUTPUT" >&2

FACTORY=$(echo "$OUTPUT" | grep -oE 'FACTORY=0x[0-9a-fA-F]{40}' | cut -d= -f2)
BASKET=$(echo "$OUTPUT" | grep -oE 'DEMO_BASKET=0x[0-9a-fA-F]{40}' | cut -d= -f2)

if [[ -z "$FACTORY" || -z "$BASKET" ]]; then
    echo "could not parse deployed addresses from forge output" >&2
    exit 1
fi

# ----- write frontend env -----

mkdir -p "$(dirname "$ENV_FILE")"
{
    echo "# auto-generated by scripts/deploy.sh ($TARGET)"
    echo "NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID"
    echo "NEXT_PUBLIC_FACTORY_ADDRESS=$FACTORY"
    echo "NEXT_PUBLIC_DEMO_BASKET_ADDRESS=$BASKET"
    if [[ "$TARGET" == "local" ]]; then
        echo "NEXT_PUBLIC_RPC_URL=http://localhost:8545"
    else
        echo "NEXT_PUBLIC_RPC_URL=$RPC_URL"
    fi
} >"$ENV_FILE"

echo "" >&2
echo "factory:     $FACTORY" >&2
echo "demo basket: $BASKET" >&2
echo "wrote $ENV_FILE" >&2
